// Defacment MITRE - T1491 

Employees
| where role == 'Web Administrator'
// Anita Bath
// MYZB-LAPTOP
// 10.10.0.8
// u/n: anbath
// e: anita_bath@framtidxdevcorp.com

ProcessEvents
| where hostname == 'MYZB-LAPTOP'
| where process_commandline has 'Shadow Truth'
// 2024-07-10T11:45:50Z when defacement happened

ProcessEvents
| where hostname == 'MYZB-LAPTOP'
| where process_commandline contains 'meme'
// First image uploaded 2024-07-10T10:53:37Z
// sha256 614ca7b627533e22aa3e5c3594605dc6fe6f000b0cc2b845ece47ca60673ec7f

FileCreationEvents
| where hostname == 'MYZB-LAPTOP'
// 9880c2d74afb2e57c7de7b9d6d0976112887502bb80344d35df34e774628dba0

OutboundNetworkEvents
| where src_ip == '10.10.0.8'
| where url contains 'frog_mall_meme'
| extend domain = parse_url(url).Host
| distinct tostring(domain)
// ronniesdankmemes.com

ProcessEvents
| where hostname == 'MYZB-LAPTOP'

// Get-ChildItem -Path C:\Users\anbath\Documents\* -Include *password* -Recurse
// mypasswordsnstuff.txt
// curl.exe -o C:\ProgramData\Heartburn\mypasswordsnstuff.txt https://newdevelopmentupdates.org/mypasswordsnstuff.txt

PassiveDns
| where domain == 'newdevelopmentupdates.org'
// 239.72.6.37

PassiveDns
| where domain == 'newdevelopmentupdates.org'
| distinct ip
| lookup PassiveDns on ip
| distinct domain
// other domains that ip resolve to - greenprojectnews.net

let TA_ips =
PassiveDns
| where domain == 'newdevelopmentupdates.org'
| distinct ip;
AuthenticationEvents
| where src_ip in (TA_ips)
| where username == 'anbath'
// using firefox 3.6.11


let TA_domains =
PassiveDns
| where domain == 'newdevelopmentupdates.org'
| distinct ip
| lookup PassiveDns on ip
| distinct domain;
Email
| where recipient == 'anita_bath@framtidxdevcorp.com'
| where link has_any(TA_domains)

OutboundNetworkEvents
| where src_ip == '10.10.0.8'
| where url == 'https://greenprojectnews.net/share/modules/files/share/enter'

OutboundNetworkEvents
| where src_ip == '10.10.0.8'
| where url startswith 'https://greenprojectnews.net/share/modules/files/share/enter'
| where url has 'username'


// Section 2
Employees
| count

Employees
| where name == "Mona Hunter"
// Johanna Karlsson - CEO
// Mona's Email - mona_hunter@framtidxdevcorp.com - 10.10.0.131

Email
| where recipient == "mona_hunter@framtidxdevcorp.com"
| count

Email
| where sender has "techinnovators.io"
| distinct sender
| count

OutboundNetworkEvents
| where src_ip == "10.10.0.131"
| distinct url
| count

PassiveDns
| where domain contains "green"
| distinct domain
| count

let dorothy_ips = Employees
| where name has "Dorothy"
| distinct ip_addr;
OutboundNetworkEvents
| where src_ip in (dorothy_ips)
| distinct url
| count

let dorothy_un = Employees
| where name has "Dorothy"
| distinct username;
AuthenticationEvents
| where username in (dorothy_un)
| count

Employees
| where role == "Chief Architect"
// Other Arch - Sofia Lindgren - 10.10.0.18 - sofia_lindgren@framtidxdevcorp.com - VJVS-MACHINE - solindgren
// Erik Bjorn - 10.10.0.3 - erik_bjorn@framtidxdevcorp.com - LRJP-DESKTOP - erbjorn

Email
| where sender has "techinnovators.io" and (recipient == "sofia_lindgren@framtidxdevcorp.com" or recipient == "erik_bjorn@framtidxdevcorp.com")

Email
| where recipient == "sofia_lindgren@framtidxdevcorp.com" or recipient == "erik_bjorn@framtidxdevcorp.com"
| summarize Count = count() by subject
| where Count > 1
//Important: Architectural Plan Changes
// alex_johnson@framtidxdevcorp.com

Email
| where subject == "Important: Architectural Plan Changes"
// greenprojectnews.net

PassiveDns
| where domain == "greenprojectnews.net"
// 239.72.6.37
// 239.72.6.38

InboundNetworkEvents
| where src_ip == "239.72.6.37" or src_ip == "239.72.6.38"
| distinct url
// 78

InboundNetworkEvents
| where src_ip == "239.72.6.37" or src_ip == "239.72.6.38" and url has "career"
// https://www.valdorianjobs.com

AuthenticationEvents
| where username == "solindgren"
// Attempt on sofia's login 2024-06-27T10:41:38Z

ProcessEvents
| where username == "solindgren"
// Remove-Item - 2024-07-09T15:58:46Z - SuperImportantMallProjectArchitecturalPlans.docx
// 2024-07-10T12:50:15Z - Invoke-WebRequest -Uri https://newdevelopmentupdates.org/fake_plans.docx -OutFile C:\Users\solindgren\Documents\fake_plans.docx
// new name - SuperImportantMallProjectArchitecturalPlans.docx

// Section 4

Employees
| where name == "Alex Johnson"
// 10.10.0.2 - alex_johnson@framtidxdevcorp.com - HWYH-LAPTOP - Developer - Hire date  2024-05-01T00:00:00Z

Email
| where sender == "alex_johnson@framtidxdevcorp.com" 
// 7
// Targets
// anita_bath@framtidxdevcorp.com
// erik_bjorn@framtidxdevcorp.com
// jennifer_owens@framtidxdevcorp.com
// johanna_karlsson@framtidxdevcorp.com
// marie_doty@framtidxdevcorp.com

let emails = dynamic(['anita_bath@framtidxdevcorp.com', 'erik_bjorn@framtidxdevcorp.com', 'jennifer_owens@framtidxdevcorp.com', 'johanna_karlsson@framtidxdevcorp.com', 'marie_doty@framtidxdevcorp.com']);
Employees
| where email_addr in (emails)
// Urgent: Security Update Required

// Taking a step back
InboundNetworkEvents
| where src_ip == "239.72.6.37" or src_ip == "239.72.6.38" and url has "Johanna"

// http://newdevelopmentupdates.org/public/signin - 10.10.0.6 - BLVR-MACHINE - Johanna Karlsson - jokarlsson
OutboundNetworkEvents
| where src_ip == "10.10.0.6" and url has "newdevelopmentupdates.org"

// 8
AuthenticationEvents
| where username == "jokarlsson"
// Threat lloged in 2024-06-27T12:40:59Z

ProcessEvents
| where hostname == "BLVR-MACHINE" and process_commandline  has "C:\\Users\\jokarlsson\\Documents\\StolenEmails\\"
// C:\Users\jokarlsson\Documents\StolenEmails\
// archive Compress-Archive -Path C:\Users\jokarlsson\Documents\StolenEmails\* -DestinationPath C:\Users\jokarlsson\Documents\StolenEmails.zip

Email
| where sender == "johanna_karlsson@framtidxdevcorp.com" and recipient == "erik.stevens@valdoriapublicworks.gov"
// erik.stevens@valdoriapublicworks.gov - exchanged many emails with johanna
// Mayor seems dirty - We're going to make so much freaking money!

// 15
ProcessEvents
| where hostname == "BLVR-MACHINE" and process_commandline  has "zip"
// Happened - 2024-07-08T14:41:47Z - div
// $emails = Get-ChildItem -Path C:\\Users\\jokarlsson\\Documents\\q\\*.eml;
//$chunks = [System.Collections.Generic.List[System.Collections.Generic.List[System.IO.FileInfo]]]::new();
//$chunkSize = 10;
//for ($i = 0; $i -lt $emails.Count; $i += $chunkSize) {
//  $chunks.Add($emails[$i..($i + $chunkSize - 1)]);
//}
//foreach ($chunk in $chunks) {
//  $chunk | Compress-Archive -DestinationPath "C:\\Users\\jokarlsson\\Documents\\Chunk$($chunks.IndexOf($chunk)).zip";
//}

Email
| where recipient has "valdoriantimes.com"

FileCreationEvents
| where hostname == "BLVR-MACHINE"

Employees

// Revisiting question 6
// Credit goes to baderalrowaiei.com for this one. Thanks for the help.
let TA_ips =
PassiveDns
| where domain has "greenprojectnews.net" or domain has "newdevelopmentupdates.org"
| distinct ip;
InboundNetworkEvents
| where src_ip in (TA_ips)
| where url contains "CEO"
| distinct url


// Q 17 and 18 
Email
| where sender has "framtidxdevcorp" and subject has "Confidential" and recipient !has "htuortwodahs@yopmail.com"
// htuortwodahs@yopmail.com
// nene.leaks@valdoriantimes.com
// Confidential Documents: Scandalous Emails Exposed on Mall Project!!!!!
